// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", false);
user_pref("app.normandy.startupRolloutPrefs.media.autoplay.default", 1);
user_pref("app.normandy.user_id", "ba8a6222-b140-3a4d-bb72-23443cbff2bd");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1555569965);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1555569605);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1555569845);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1555569725);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1555569575);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{37022dfe-2587-8745-8486-4ca19cd8bfd0}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1555513200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1555569625903");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1555571430903");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1555569581543");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1555573181543");
user_pref("browser.search.region", "JP");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1555569579");
user_pref("browser.slowStartup.averageTime", 2816);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190409155332");
user_pref("browser.startup.homepage_override.mstone", "66.0.3");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1555569580653");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.3");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.push.userAgentID", "076678bd4674485297e880b48b501733");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "66.0.3");
user_pref("extensions.lastPlatformVersion", "66.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"509928b7-bcf1-e148-bd7a-04316fdfefbf\",\"screenshots@mozilla.org\":\"a27bb193-eef2-f046-993e-b4c1182d048e\",\"webcompat-reporter@mozilla.org\":\"1eeda499-6e56-a845-bfbf-13e4148f254b\",\"webcompat@mozilla.org\":\"2b5d6378-fbfb-d84c-acc4-d87ed9fd150f\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1555570043);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190409155332");
user_pref("media.gmp-manager.lastCheck", 1555570043);
user_pref("media.gmp-widevinecdm.abi", "x86_64-gcc3");
user_pref("media.gmp-widevinecdm.lastUpdate", 1555570046);
user_pref("media.gmp-widevinecdm.version", "4.10.1196.0");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "fc540585-783b-1e4b-a59d-00dad502d09b");
user_pref("security.sandbox.plugin.tempDirSuffix", "9fa33d87-41ff-204d-9916-4aae772668c0");
user_pref("services.blocklist.addons.checked", 1555570041);
user_pref("services.blocklist.gfx.checked", 1555570041);
user_pref("services.blocklist.onecrl.checked", 1555570041);
user_pref("services.blocklist.pinning.checked", 1555570041);
user_pref("services.blocklist.plugins.checked", 1555570041);
user_pref("services.settings.clock_skew_seconds", 2);
user_pref("services.settings.last_etag", "\"1555540287852\"");
user_pref("services.settings.last_update_seconds", 1555570041);
user_pref("services.settings.main.language-dictionaries.last_check", 1555570041);
user_pref("services.settings.main.onboarding.last_check", 1555570041);
user_pref("services.settings.main.sites-classification.last_check", 1555570041);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1555569574);
user_pref("toolkit.telemetry.cachedClientID", "8872f091-f163-f648-8a29-6d0d6e0389e3");
user_pref("toolkit.telemetry.previousBuildID", "20190409155332");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
